-- Table definitions for the tournament project.
--
-- Put your SQL 'create table' statements in this file; also 'create view'
-- statements if you choose to use it.
--
-- You can write comments in this file by starting them with two dashes, like
-- these lines here.

--check if database already exists
DROP DATABASE IF EXISTS tournament;

--create db
CREATE DATABASE tournament;

--connect to db tournament
\c tournament

-- A TABLE THAT HAS THE PLAYERS' INFORMATION
CREATE TABLE PLAYERS
(

PLAYER_ID SERIAL PRIMARY KEY, --primary key

--Players
NAME TEXT --name of players

--Number of wins
--WINS INT,

--Number of losses
--LOSSES INT,

--Number of games played
--GAMES_PLAYED INT

);

-- A TABLE THAT HAS THE MATCHES' INFORMATION
CREATE TABLE MATCHES
(

MATCH_ID SERIAL PRIMARY KEY, --PRIMARY KEY OF MATCHES

WINNER INT REFERENCES PLAYERS(PLAYER_ID), --WINNER OF MATCH

LOSER INT REFERENCES PLAYERS(PLAYER_ID) --WINNER OF MATCH

--ROUND INT --ROUND THAT THE MATCH TOOK PLACE IN

);

CREATE VIEW PLAYER_WINS AS
SELECT PLAYERS.PLAYER_ID, PLAYERS.NAME, COUNT(MATCHES.WINNER) AS WINS
FROM PLAYERS LEFT JOIN MATCHES ON PLAYERS.PLAYER_ID=MATCHES.WINNER
GROUP BY PLAYER_ID
ORDER BY WINS;

CREATE VIEW PLAYER_GAMES AS
SELECT PLAYERS.PLAYER_ID, PLAYERS.NAME, COUNT(MATCHES.*) AS GAMES_PLAYED
FROM PLAYERS LEFT JOIN MATCHES 
ON PLAYERS.PLAYER_ID=MATCHES.WINNER OR PLAYERS.PLAYER_ID=MATCHES.LOSER
GROUP BY PLAYER_ID;

CREATE VIEW STANDINGS AS
SELECT PLAYER_WINS.*, PLAYER_GAMES.GAMES_PLAYED
FROM PLAYER_WINS, PLAYER_GAMES
WHERE PLAYER_WINS.PLAYER_ID=PLAYER_GAMES.PLAYER_ID
ORDER BY WINS;
